FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env

WORKDIR /app

COPY database/ database/
COPY manager/ manager/

RUN dotnet restore /app/manager/
RUN dotnet publish /app/manager/ --no-restore -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "manager.dll"]
