name: poc

services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  api:
    container_name: api
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Username=postgres;Password=changeme;Database=postgres;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true
    ports:
      - "5000:8080"
    networks:
      - postgres


  # TODO manager

networks:
  postgres:
    driver: bridge